# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3e638f00807756cee8dca1c76e70ef8bef2437fd4065ca4c4f8d331033e56e26a86a40cb2a01af5423838b24dadc450fd6534a440749c4593c781870c178d1a9

test:
  secret_key_base: b5b89aa306e75b5bcfda3e25e4b8b203fd110bc931c0cf90f46bbba848023f97ee94195ef01be6f0f54fc0c43681e06b1b844afb82d4a0815a338f760504af5e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
